name: superbaleia
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  responsive_grid: ^2.0.0
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.3
  http: ^0.12.2
  get_storage: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
      - family: black
        fonts:
          - asset: assets/fonts/black.otf

      - family: bold
        fonts:
          - asset: assets/fonts/bold.ttf

      - family: heavy
        fonts:
          - asset: assets/fonts/heavy.otf

      - family: light
        fonts:
          - asset: assets/fonts/light.ttf

      - family: medium
        fonts:
          - asset: assets/fonts/medium.otf

      - family: regular
        fonts:
          - asset: assets/fonts/regular.otf

      - family: semiBold
        fonts:
          - asset: assets/fonts/semiBold.otf

      - family: thin
        fonts:
          - asset: assets/fonts/thin.otf

      - family: light
        fonts:
          - asset: assets/fonts/ultralight.otf
